# General Jekyll Config
highlighter: rogue
name: J Sha
description: Coding Experiments
url: "http://docjsha.github.io/"
lsi: fale

exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

# Build settings
permalink: pretty

theme: jekyll-theme-tactile
