# Site settings
title: J Sha blog
email: 
description: "Musings of a Machine Learning Practioner"
baseurl: ""
url: "http://docjsha.github.io"
twitter_username: docjsha
github_username:  docjsha

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
